const COLORS = {
  WHITE: '#FFFFFF',
  CURRENCY_TOP_TITLE: '#1F3F66',

  MAIN: {
    MAIN_VALUE: '#1F3F66',
    SECTION_HEADER: '#7A8899',
    LIST_ITEM_TITLE: '#242B33',
    LIST_ITEM_SUBTITLE: '#8A9199',
    LIST_ITEM_VALUE: '#1F2833'
  },

  BOTTOM_MENU: {
    ICON_FILL: '#8F9FB3'
  },

  HEADER: {
    BACK_BTN: '#2E3C4D'
  },

  EXPENDITURE: {
    TYPE_BTN_TEXT_ENABLED: '#2E3C4D',
    TYPE_BTN_TEXT_DISABLED: '#7A8899'
  }
};

export default COLORS;
